### ISSUE TITLE
FigureImageView的使用存在问题

### ISSUE THREAD

**Issue by apkcore** [Idtk/FigureImageView#1]
FigureImageView的使用中，在设置model=sector时图片显示有问题，model=ring时显示的反而是个扇形，是不是与我使用的是长方形的图片有关

**Comment by Idtk** [comment]
谢谢反馈，是因为mPath1使用之后没有清空的原因所致，已经修复

**Comment by apkcore** [comment]
加上了mpath1.reset此问题依然存在。。。

**Comment by Idtk** [comment]
需要在sector与ring的情况下都增加，我源码已经更新了，你可以下载下来试试

**Comment by apkcore** [comment]
我试了，在我的5.0手机上正常，在4.4的手机上还是存在

**Comment by Idtk** [comment]
在sector与ring使用前再清理一次mPath1，4.4即可正常使用

**Comment by apkcore** [comment]
用最新的代码还是不行，我改了下
case SECTOR:
                mPath1.reset();
                rectF.left = -length \* 2;
                rectF.top = -length;
                rectF.right = length \* 2;
                rectF.bottom = length \* 3;
                mPath1.moveTo(0, length);
                mPath1.arcTo(rectF, angle, -angle \* 2 - 180);
                mPath1.addRect(-mViewWidth / 2, -mViewHeight / 2, mViewWidth / 2, mViewHeight / 2, Path.Direction.CCW);
                mPath.op(mPath1, Path.Op.INTERSECT);
                mPath1.reset();
                break;
            case RING:
                mPath1.reset();
                rectF.left = -length \* 2;
                rectF.top = -length;
                rectF.right = length \* 2;
                rectF.bottom = length \* 3;
                mPath1.moveTo(0, length);
                mPath1.arcTo(rectF, angle, -angle \* 2 - 180);

```
            rectF.left = -length / 2;
            rectF.top = length / 2;
            rectF.right = length / 2;
            rectF.bottom = length * 3 / 2;
            mPath2.moveTo(0, length);
            mPath2.arcTo(rectF, angle, -angle * 2 - 180);

            mPath1.op(mPath2, Path.Op.XOR);
            mPath.op(mPath1, Path.Op.XOR);
            mPath1.reset();
```

这样就可以了，但是在RING的时候，仔细看上面有根很细的线，不知道怎么来的

**Comment by Idtk** [comment]
这个其实是一样的，A异或0 = A 。我查了下我这边的手机确实没有问题，所以你需要提供给我截图和手机型号才好。最好给我个联系方式，可以发到我的邮箱.。

**Comment by apkcore** [comment]
985076456秋秋，已发送到你的gmail邮箱
